### ISSUE TITLE
Extract module from connector and implement basic API

### ISSUE THREAD

**Issue by justmoon** [interledger/js-ilp-core#1]
Most of the functionality for this module already exists as part of interledger/five-bells-connector. Need to extract it and make sure the external API conforms to the [API mockup](https://gist.github.com/justmoon/4cffdd01fce7f26a68e64e5bab0bb3f3).

**Comment by emschwartz** [comment]
@justmoon This is done, right?

**Comment by justmoon** [comment]
Yep
