### ISSUE TITLE
Should we add event for when money is received?

### ISSUE THREAD

**Issue by emschwartz** [interledger/js-ilp-core#10]
Right now it seems like it would be easy to misunderstand the meaning of the `receive` event. It can either mean that you received money, in the case of an optimistic payment, or that you received a conditional transfer (and _not_ money) that you need to submit the fulfillment for or wait for the `fulfill_execution_condition` event.

Should `js-ilp` or `js-ilp-core` have events that indicate whether money has actually been received? @justmoon

**Comment by justmoon** [comment]
Agree, I think that would go into `ilp`, since it's a feature related to the receiver use case. (The connector doesn't care whether it got paid or not, it will forward the payment either way.)
