### ISSUE TITLE
Should we add a maxSourceHoldDuration feature?

### ISSUE THREAD

**Issue by emschwartz** [interledger/js-ilp-core#9]
Right now the core client will let you send a payment that puts your money on hold for an unlimited amount of time. Either the `js-ilp` client or the `js-ilp-core` client should have a `maxSourceHoldDuration` feature (with a default to something like 10 seconds) that stops you from accidentally agreeing to lock your money up indefinitely.

Should this go in core or the client? @justmoon

**Comment by justmoon** [comment]
I would say that would go into `ilp` since `ilp-core` would be used by something like the connector which has more complex logic around acceptable hold times anyway.
